# /.devcontainer/docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: ../ # This tells Docker to go up one directory to the project root
      dockerfile: Dockerfile # Looks for a Dockerfile in that root directory
    volumes:
      - ../:/usr/src/app # Mounts the entire project to the container
    ports:
      - "3000:3000"
    command: npm run dev --prefix ./04-Application/backend
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: accounting_db
      DB_PORT: 5432
    depends_on:
      - db
  
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: accounting_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: